[package]
name = "rempref"
version = "0.1.0"
edition = "2021"
authors = ["Attila Sz≈ëke"]
description = "A file prefix removal utility"

[dependencies]
structopt = "0.3.26"
nu-glob = "0.63.0"
thiserror = "1.0.31"
pathdiff = "0.2.1"