[package]
name = "denest"
version = "0.2.0"
edition = "2021"
authors = ["Attila Sz≈ëke"]
description = "Nested file hoister utility"

[dependencies]
commons = { path = "../commons" }
structopt = "0.3.26"
